<a href='http://moncoachdata.com'><img src= 'https://moncoachdata.com/wp-content/uploads/MonCoachData-cours/MonCoachData.jpg' width=400/></a>


---


<center><em>Copyright MonCoachData (tous droits réservés)</em></center>
<center><em>Pour plus d'informations, visitez notre site <a href='http://moncoachdata.com'>moncoachdata.com</a></em></center>



---

# NumPy 

NumPy est une puissante bibliothèque d'algèbre linéaire pour Python. Ce qui la rend si importante, c'est que presque toutes les bibliothèques de l'écosystème <a href='https://pydata.org/'>PyData</a> (pandas, scipy, scikit-learn, etc.) comptent sur NumPy comme l'un de leurs principaux éléments constitutifs. De plus, nous l'utiliserons pour générer des données pour nos exemples d'analyse plus tard !

NumPy est également incroyablement rapide, car il a des liens avec les bibliothèques C. Pour plus d'informations sur les raisons pour lesquelles vous souhaitez utiliser des tableaux au lieu de listes, consultez ce super [post StackOverflow](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

Ici, nous n'apprendrons que les bases de NumPy.

## Utilisation de NumPy

Une fois que vous avez installé NumPy (pré-installée sur Google Colab et sur la distribution Anaconda), vous pouvez l'importer comme bibliothèque :

In [ ]:
import numpy as np

NumPy possède de nombreuses fonctions et capacités intégrées. Nous ne les couvrirons pas toutes, mais nous nous concentrerons sur certains des aspects les plus importants de NumPy : les vecteurs, les tableaux, les matrices et la génération de nombres. Commençons par parler des matrices.

# Tableaux NumPy

La forme de tableaux NumPy est la principale façon dont nous utiliserons NumPy tout au long de ce cours. Les matrices NumPy se présentent essentiellement sous deux formes : les vecteurs et les matrices. Les vecteurs sont strictement des tableaux à une dimension (1D) et les matrices sont à deux dimensions (mais vous devez noter qu'une matrice peut toujours avoir une seule ligne ou une seule colonne).

Commençons notre introduction en explorant la manière de créer des tableaux NumPy.

## Création de tableaux NumPy

### depuis une liste Python

On peut créer un tableau en convertissant directement une liste ou une liste de listes :

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Méthodes intégrées

Il existe de nombreuses façons intégrées de générer des tableaux.

### arange

Retourne des valeurs uniformément espacées dans un intervalle donné. [[référence](https://numpy.org/doc/1.18/reference/generated/numpy.arange.html)]

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros et ones

Générer des tableaux de zéros ou de uns. [[référence](https://numpy.org/devdocs/reference/generated/numpy.zeros.html)]

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace 
Retourne des nombres uniformément espacés sur un intervalle donné. [[référence](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

<font color=green>Il est à noter que `.linspace()` *inclus* la valeur stop. Pour obtenir un tableau de fractions plus courantes (ex. 0.5 ou 0.25), augmentez le nombre d'éléments :</font>

In [ ]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

### eye

Crée une matrice d'identité [[référence](https://numpy.org/doc/1.18/reference/generated/numpy.eye.html)]

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## random 
NumPy a également de nombreuses façons de créer des tableaux de nombres aléatoires :

### rand
Crée un tableau de la forme donnée et le remplit avec des échantillons aléatoires provenant d'une distribution uniforme sur ``[0, 1]``. [[référence](https://numpy.org/doc/1.18/reference/random/generated/numpy.random.rand.html)]

In [ ]:
np.random.rand(2)

array([0.43558875, 0.4096659 ])

In [ ]:
np.random.rand(5,5)

array([[0.46651371, 0.05824751, 0.86962177, 0.954317  , 0.2384495 ],
       [0.50525371, 0.37348571, 0.42743294, 0.52156267, 0.78020498],
       [0.03965934, 0.01618178, 0.85138255, 0.83459895, 0.94183436],
       [0.78969282, 0.79793776, 0.48691103, 0.25991003, 0.40832838],
       [0.41695104, 0.51492553, 0.32162993, 0.50071826, 0.40962454]])

### randn

Retourne un échantillon (ou des échantillons) de la distribution "normale standard" [σ = 1]. Contrairement à **rand** qui est uniforme, des valeurs plus proches de zéro sont plus susceptibles d'apparaître. [[référence](https://numpy.org/devdocs/reference/random/generated/numpy.random.randn.html)]

In [ ]:
np.random.randn()

-0.42919875128118057

In [ ]:
np.random.randn(2)

array([ 0.89406303, -0.16657058])

In [ ]:
np.random.randn(5,5)

array([[ 0.86599315, -0.49079569,  0.49232774, -0.75505639, -0.18373974],
       [ 1.79467634, -0.50354046, -0.04698048, -0.20829702,  0.1019792 ],
       [ 0.53252159,  2.13014574,  0.034848  , -0.478428  ,  1.24842248],
       [ 0.42664748, -0.92482525,  0.05142856,  0.20102228, -0.6980305 ],
       [ 0.74641747, -2.02065422,  0.37111649, -0.22027115, -0.9927488 ]])

### randint
Retourne des entiers aléatoires de `low` (inclus) to `high` (exclus).  [[référence](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html)]

In [ ]:
np.random.randint(1,100)

30

In [ ]:
np.random.randint(1,100,10)

array([66, 30, 65, 42, 39, 40, 13, 77, 70, 58])

### seed
Peut être utilisé pour définir l'état aléatoire, de sorte que les mêmes résultats "aléatoires" puissent être reproduits. [[référence](https://numpy.org/devdocs/reference/random/generated/numpy.random.seed.html)]

In [ ]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

## Attributs et méthodes des tableaux

Examinons quelques attributs et méthodes utiles pour un tableau :

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

## Reshape
Retourne un tableau contenant les mêmes données avec une forme (nombre de lignes et colonnes) différente. [[référence](https://numpy.org/doc/1.18/reference/generated/numpy.reshape.html)]

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

Ce sont des méthodes utiles pour trouver des valeurs maximales ou minimales. Ou pour trouver l'emplacement de leur indice en utilisant argmin ou argmax

In [ ]:
ranarr

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

In [ ]:
ranarr.max()

43

In [ ]:
ranarr.argmax()

7

In [ ]:
ranarr.min()

1

In [ ]:
ranarr.argmin()

5

## Shape

shape est un attribut que possèdent les tableaux (et non une méthode) :  [[référence](https://numpy.org/devdocs/reference/generated/numpy.shape.html)]

In [ ]:
# Vecteur
arr.shape

(25,)

In [ ]:
# Remarquez les doubles crochets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

### dtype

Vous pouvez également saisir le type de données de l'objet dans le tableau : [[référence](https://numpy.org/doc/1.18/reference/generated/numpy.dtype.html)]

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')