<a href='http://moncoachdata.com'><img src= 'https://moncoachdata.com/wp-content/uploads/MonCoachData-cours/MonCoachData.jpg' width=400/></a>


---


<center><em>Copyright MonCoachData (tous droits réservés)</em></center>
<center><em>Pour plus d'informations, visitez notre site <a href='http://moncoachdata.com'>moncoachdata.com</a></em></center>



---

# Indexation et Sélection NumPy

Dans cette session, nous discuterons de la manière de sélectionner des éléments ou des groupes d'éléments dans un tableau.

In [ ]:
import numpy as np

In [ ]:
# Création d'un tableau d'échantillons
arr = np.arange(0,11)

In [ ]:
# Affichage
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexation et Sélection avec crochets (bracket)
La façon la plus simple de choisir un ou plusieurs éléments d'un tableau ressemble beaucoup aux listes python :

In [ ]:
# Obtenir une valeur correspondant à un certain indice
arr[8]

8

In [ ]:
# Obtenir des valeurs dans un intervalle
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
# Obtenir des valeurs dans un intervalle
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Les tableaux NumPy diffèrent des listes Python normales en raison de leur capacité à diffuser. Avec les listes, vous ne pouvez réassigner que des parties d'une liste avec de nouvelles parties de même taille et de même forme. Autrement dit, si vous vouliez remplacer les 5 premiers éléments d'une liste par une nouvelle valeur, vous devriez passer dans une nouvelle liste de 5 éléments. Avec les tableaux NumPy, vous pouvez diffuser une seule valeur sur un ensemble plus large de valeurs :

In [ ]:
# Définir une valeur avec un intervalle d'index (broadcasting)
arr[0:5] = 100

# Affichage
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
# Réinitialiser le tableau, nous verrons pourquoi j'ai dû le faire dans un instant
arr = np.arange(0,11)

# Affichage
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Notes importantes sur les tranches (slicing)
slice_of_arr = arr[0:6]

# Afficher la tranche
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
# Changer la tranche
slice_of_arr[:] = 99

# l'afficher de nouveau
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Notez maintenant que les changements se produisent également dans notre tableau d'origine !

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Les données ne sont pas copiées, c'est une vue du tableau d'origine ! Cela évite les problèmes de mémoire !

In [ ]:
# Pour obtenir une copie, il faut être explicite
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexation d'un tableau 2D (matrices)

Le format général est **arr_2d[row][col]** ou **arr_2d[row,col]**. Je recommande d'utiliser la notation avec la virgule pour plus de clarté.

In [ ]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

# Affichage
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
# Indexation de ligne
arr_2d[1]

array([20, 25, 30])

In [ ]:
# Le format est arr_2d[row][col] ou arr_2d[row,col]

# Obtenir la valeur d'un élément individuel
arr_2d[1][0]

20

In [ ]:
# Obtenir la valeur d'un élément individuel
arr_2d[1,0]

20

In [ ]:
# Découpage de tableaux en 2D

# Shape (2,2) à partir du coin supérieur droit
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
# rangée du bas
arr_2d[2]

array([35, 40, 45])

In [ ]:
# Identique - rangée du bas
arr_2d[2,:]

array([35, 40, 45])

## Un peu d'aide pour l'indexation
L'indexation d'une matrice 2D peut être un peu déroutante au début, surtout quand on commence à ajouter des pas. Essayez la recherche d'images sur Google, par exemple *NumPy indexing* pour trouver des images utiles, comme celle-ci :

<img src= 'https://drive.google.com/uc?export=view&id=1hGCSxCYIHuAKQHrLgrVcA5B4-aZ0VQi2' width=500/>

## Sélection conditionnelle

C'est un concept très fondamental qui se traduira directement avec Pandas plus tard, assurez-vous de bien comprendre cette partie !

Voyons brièvement comment utiliser des crochets pour la sélection basée sur des opérateurs de comparaison.

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr > 4

In [ ]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = 2
arr[arr > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])